spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: myspringcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: myspringcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

